title: Zhenyu Zhang's Homepage
page-top-title: Zhenyu Zhang
top-section-bg-text: Agricultural Information Engineering
home-subtitle: Zhenyu Zhang&ensp;|&ensp;张振宇
copyright-text: '&copy; Zhenyu Zhang 2023-2025. All Rights Reserved.'
